BASICAUTH=g9CZRkDEC5x8vfr96HMvkR3oiEiPLW:ECepRGahbgUCnwH5rCC7Xk3fdkBCKu

# *** ADMIN ACCOUNT ***

echo "Admin: Juan"
JUANTOKEN=$(curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/auth/signup -H "Content-Type: application/json" -d '{"UserName": "Juan", "Password": "qqqqqqqq"}' | python -c "import sys, json; print json.load(sys.stdin)['Token']") > /dev/null
curl -s -u ${BASICAUTH} --request PATCH http://www.digitalwizardry.ca:5001/api/account -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", AccountType: "ADMIN" }' > /dev/null

# *** COACH ACCOUNTS ***

echo "Coach: Ivan"
IVANTOKEN=$(curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/auth/signup -H "Content-Type: application/json" -d '{"UserName": "Ivan", "Password": "qqqqqqqq"}' | python -c "import sys, json; print json.load(sys.stdin)['Token']") > /dev/null
curl -s -u ${BASICAUTH} --request PATCH http://www.digitalwizardry.ca:5001/api/account -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Ivan", AccountType: "COACH" }' > /dev/null

echo "Coach: Lisa"
LISATOKEN=$(curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/auth/signup -H "Content-Type: application/json" -d '{"UserName": "Lisa", "Password": "qqqqqqqq"}' | python -c "import sys, json; print json.load(sys.stdin)['Token']") > /dev/null
curl -s -u ${BASICAUTH} --request PATCH http://www.digitalwizardry.ca:5001/api/account -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Lisa", AccountType: "COACH" }' > /dev/null

# *** JOGGER ACCOUNTS ***

echo "Jogger: Robb"
ROBBTOKEN=$(curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/auth/signup -H "Content-Type: application/json" -d '{"UserName": "Robb", "Password": "qqqqqqqq", "AccountType": "JOGGER"}' | python -c "import sys, json; print json.load(sys.stdin)['Token']") > /dev/null

echo "Jogger: Emily"
EMILYTOKEN=$(curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/auth/signup -H "Content-Type: application/json" -d '{"UserName": "Emily", "Password": "qqqqqqqq", "AccountType": "JOGGER"}' | python -c "import sys, json; print json.load(sys.stdin)['Token']") > /dev/null

echo "Jogger: James"
JAMESTOKEN=$(curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/auth/signup -H "Content-Type: application/json" -d '{"UserName": "James", "Password": "qqqqqqqq", "AccountType": "JOGGER"}' | python -c "import sys, json; print json.load(sys.stdin)['Token']") > /dev/null

echo "Jogger: Zoe"
ZOETOKEN=$(curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/auth/signup -H "Content-Type: application/json" -d '{"UserName": "Zoe", "Password": "qqqqqqqq", "AccountType": "JOGGER"}' | python -c "import sys, json; print json.load(sys.stdin)['Token']") > /dev/null

# *** JOGS ***

echo "Jogs: Juan"
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-10 1:38:14 PM", "Distance": 6.43, "Time": 3170 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-09 1:38:14 PM", "Distance": 8.12, "Time": 2695 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-08 1:38:14 PM", "Distance": 2.1, "Time": 1950 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-07 1:38:14 PM", "Distance": 1.48, "Time": 3333 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-06 1:38:14 PM", "Distance": 12.71, "Time": 4444 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-05 1:38:14 PM", "Distance": 11.49, "Time": 5555 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-04 1:38:14 PM", "Distance": 6.97, "Time": 6666 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-03 1:38:14 PM", "Distance": 2.99, "Time": 777 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-02 1:38:14 PM", "Distance": 0.34, "Time": 888 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JUANTOKEN}"'", "UserName": "Juan", "Date": "2017-05-01 1:38:14 PM", "Distance": 1.1, "Time": 999 }' > /dev/null

echo "Jogs: Ivan"
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-10 1:38:14 PM", "Distance": 4.13, "Time": 3456 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-09 1:38:14 PM", "Distance": 5.62, "Time": 5544 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-08 1:38:14 PM", "Distance": 8.74, "Time": 334 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-07 1:38:14 PM", "Distance": 14.33, "Time": 5456 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-06 1:38:14 PM", "Distance": 13.33, "Time": 3434 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-05 1:38:14 PM", "Distance": 3.33, "Time": 5555 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-04 1:38:14 PM", "Distance": 6.45, "Time": 5434 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-03 1:38:14 PM", "Distance": 3.19, "Time": 454 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-02 1:38:14 PM", "Distance": 1.34, "Time": 499 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${IVANTOKEN}"'", "UserName": "Ivan", "Date": "2017-05-01 1:38:14 PM", "Distance": 11.11, "Time": 984 }' > /dev/null

echo "Jogs: Lisa"
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-10 1:38:14 PM", "Distance": 9.55, "Time": 2345 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-09 1:38:14 PM", "Distance": 10.12, "Time": 2345 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-08 1:38:14 PM", "Distance": 3.92, "Time": 345 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-07 1:38:14 PM", "Distance": 12.68, "Time": 2345 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-06 1:38:14 PM", "Distance": 13.61, "Time": 5433 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-05 1:38:14 PM", "Distance": 11.29, "Time": 6784 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-04 1:38:14 PM", "Distance": 2.27, "Time": 4456 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-03 1:38:14 PM", "Distance": 4.59, "Time": 456 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-02 1:38:14 PM", "Distance": 1.84, "Time": 643 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${LISATOKEN}"'", "UserName": "Lisa", "Date": "2017-05-01 1:38:14 PM", "Distance": 18.2, "Time": 775 }' > /dev/null

echo "Jogs: Robb"
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-10 1:38:14 PM", "Distance": 10.53, "Time": 3470 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-09 1:38:14 PM", "Distance": 8.02, "Time": 2635 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-08 1:38:14 PM", "Distance": 2.94, "Time": 950 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-07 1:38:14 PM", "Distance": 17.48, "Time": 5449 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-06 1:38:14 PM", "Distance": 17.71, "Time": 5999 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-05 1:38:14 PM", "Distance": 18.49, "Time": 5852 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-04 1:38:14 PM", "Distance": 6.17, "Time": 2154 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-03 1:38:14 PM", "Distance": 2.09, "Time": 740 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-02 1:38:14 PM", "Distance": 0.74, "Time": 267 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-05-01 1:38:14 PM", "Distance": 15.1, "Time": 5324 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-30 1:38:14 PM", "Distance": 1.49, "Time": 501 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-29 1:38:14 PM", "Distance": 9.08, "Time": 3301 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-28 1:38:14 PM", "Distance": 7.3, "Time": 2345 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-27 1:38:14 PM", "Distance": 13.99, "Time": 4576 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-26 1:38:14 PM", "Distance": 16.37, "Time": 5070 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-25 1:38:14 PM", "Distance": 11.74, "Time": 3988 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-24 1:38:14 PM", "Distance": 18.47, "Time": 6005 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-23 1:38:14 PM", "Distance": 16.28, "Time": 5735 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-22 1:38:14 PM", "Distance": 3.86, "Time": 1211 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-21 1:38:14 PM", "Distance": 5.72, "Time": 1844 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-20 1:38:14 PM", "Distance": 1.07, "Time": 340 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-19 1:38:14 PM", "Distance": 2.53, "Time": 873 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-18 1:38:14 PM", "Distance": 3.68, "Time": 1178 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-17 1:38:14 PM", "Distance": 2.21, "Time": 783 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-16 1:38:14 PM", "Distance": 18.45, "Time": 6664 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-15 1:38:14 PM", "Distance": 12.35, "Time": 4363 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-14 1:38:14 PM", "Distance": 18.83, "Time": 6507 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-13 1:38:14 PM", "Distance": 17.24, "Time": 6176 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-12 1:38:14 PM", "Distance": 2.31, "Time": 783 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-11 1:38:14 PM", "Distance": 4.42, "Time": 1492 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-10 1:38:14 PM", "Distance": 19.71, "Time": 6843 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-09 1:38:14 PM", "Distance": 1.93, "Time": 600 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-08 1:38:14 PM", "Distance": 16.36, "Time": 5419 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-07 1:38:14 PM", "Distance": 17.91, "Time": 5817 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-06 1:38:14 PM", "Distance": 8.3, "Time": 2582 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-05 1:38:14 PM", "Distance": 19.02, "Time": 6714 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-04 1:38:14 PM", "Distance": 15.11, "Time": 5443 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-03 1:38:14 PM", "Distance": 2.38, "Time": 822 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-02 1:38:14 PM", "Distance": 6.37, "Time": 2250 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-04-01 1:38:14 PM", "Distance": 16.36, "Time": 5347 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-31 1:38:14 PM", "Distance": 12.3, "Time": 4059 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-30 1:38:14 PM", "Distance": 13.82, "Time": 4400 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-29 1:38:14 PM", "Distance": 6.78, "Time": 2288 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-28 1:38:14 PM", "Distance": 8.92, "Time": 2907 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-27 1:38:14 PM", "Distance": 15.79, "Time": 5067 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-26 1:38:14 PM", "Distance": 1.23, "Time": 390 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-25 1:38:14 PM", "Distance": 13.02, "Time": 4091 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-24 1:38:14 PM", "Distance": 14.36, "Time": 4563 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-23 1:38:14 PM", "Distance": 13.81, "Time": 4847 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ROBBTOKEN}"'", "UserName": "Robb", "Date": "2017-03-22 1:38:14 PM", "Distance": 9.51, "Time": 3094 }' > /dev/null

echo "Jogs: Emily"
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-10 1:38:17 PM", "Distance": 6.8, "Time": 3882 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-09 1:38:17 PM", "Distance": 1.01, "Time": 466 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-08 1:38:17 PM", "Distance": 13.99, "Time": 7550 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-07 1:38:17 PM", "Distance": 2.86, "Time": 1299 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-06 1:38:17 PM", "Distance": 6.78, "Time": 3083 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-05 1:38:17 PM", "Distance": 19.98, "Time": 10901 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-04 1:38:17 PM", "Distance": 13.34, "Time": 6291 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-03 1:38:17 PM", "Distance": 12.12, "Time": 6873 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-02 1:38:17 PM", "Distance": 7.9, "Time": 3746 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-05-01 1:38:17 PM", "Distance": 18.64, "Time": 8687 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-30 1:38:17 PM", "Distance": 9.75, "Time": 5428 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-29 1:38:17 PM", "Distance": 4.16, "Time": 2047 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-28 1:38:17 PM", "Distance": 4.83, "Time": 2705 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-27 1:38:17 PM", "Distance": 16.66, "Time": 8112 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-26 1:38:17 PM", "Distance": 19.67, "Time": 9268 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-25 1:38:17 PM", "Distance": 10.47, "Time": 5612 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-24 1:38:17 PM", "Distance": 6.89, "Time": 3145 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-23 1:38:17 PM", "Distance": 7.5, "Time": 3996 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-22 1:38:17 PM", "Distance": 18.42, "Time": 9102 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-21 1:38:17 PM", "Distance": 7.48, "Time": 4207 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-20 1:38:17 PM", "Distance": 1.73, "Time": 873 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-19 1:38:17 PM", "Distance": 2.07, "Time": 1038 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-18 1:38:17 PM", "Distance": 16.51, "Time": 7405 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-17 1:38:17 PM", "Distance": 2.27, "Time": 1074 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-16 1:38:17 PM", "Distance": 6.97, "Time": 3532 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-15 1:38:17 PM", "Distance": 8.17, "Time": 4128 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-14 1:38:17 PM", "Distance": 3.98, "Time": 1938 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-13 1:38:17 PM", "Distance": 11.9, "Time": 6350 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-12 1:38:17 PM", "Distance": 15.92, "Time": 7985 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-11 1:38:17 PM", "Distance": 11.84, "Time": 5734 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-10 1:38:17 PM", "Distance": 7.46, "Time": 3697 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-09 1:38:17 PM", "Distance": 18.36, "Time": 8968 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-08 1:38:17 PM", "Distance": 7.49, "Time": 3509 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-07 1:38:17 PM", "Distance": 16.43, "Time": 7668 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-06 1:38:17 PM", "Distance": 7.32, "Time": 3800 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-05 1:38:17 PM", "Distance": 2.12, "Time": 975 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-04 1:38:17 PM", "Distance": 6.88, "Time": 3144 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-03 1:38:17 PM", "Distance": 14.1, "Time": 7998 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-02 1:38:17 PM", "Distance": 19.78, "Time": 9373 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-04-01 1:38:17 PM", "Distance": 14.76, "Time": 7804 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-31 1:38:17 PM", "Distance": 19.14, "Time": 10612 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-30 1:38:17 PM", "Distance": 5.19, "Time": 2571 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-29 1:38:17 PM", "Distance": 6.72, "Time": 3769 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-28 1:38:17 PM", "Distance": 0.64, "Time": 301 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-27 1:38:17 PM", "Distance": 5.74, "Time": 3165 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-26 1:38:17 PM", "Distance": 9.16, "Time": 4657 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-25 1:38:17 PM", "Distance": 19.12, "Time": 9008 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-24 1:38:17 PM", "Distance": 13.66, "Time": 6743 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-23 1:38:17 PM", "Distance": 10.89, "Time": 5433 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${EMILYTOKEN}"'", "UserName": "Emily", "Date": "2017-03-22 1:38:17 PM", "Distance": 2.26, "Time": 1270 }' > /dev/null

echo "Jogs: James"
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-10 1:38:20 PM", "Distance": 18.63, "Time": 9452 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-09 1:38:20 PM", "Distance": 14.31, "Time": 7019 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-08 1:38:20 PM", "Distance": 4.81, "Time": 2359 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-07 1:38:20 PM", "Distance": 14.76, "Time": 8101 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-06 1:38:20 PM", "Distance": 16.22, "Time": 8095 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-05 1:38:20 PM", "Distance": 13.21, "Time": 6282 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-04 1:38:20 PM", "Distance": 8.79, "Time": 4809 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-03 1:38:20 PM", "Distance": 15.63, "Time": 7600 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-02 1:38:20 PM", "Distance": 17.86, "Time": 8700 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-05-01 1:38:20 PM", "Distance": 4.53, "Time": 2144 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-30 1:38:20 PM", "Distance": 12.62, "Time": 6586 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-29 1:38:20 PM", "Distance": 19.58, "Time": 11092 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-28 1:38:20 PM", "Distance": 17.4, "Time": 7983 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-27 1:38:20 PM", "Distance": 2.95, "Time": 1615 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-26 1:38:20 PM", "Distance": 3.92, "Time": 1956 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-25 1:38:20 PM", "Distance": 6.58, "Time": 3166 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-24 1:38:20 PM", "Distance": 3.66, "Time": 2007 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-23 1:38:20 PM", "Distance": 9.45, "Time": 5385 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-22 1:38:20 PM", "Distance": 9.1, "Time": 4456 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-21 1:38:20 PM", "Distance": 19.57, "Time": 10203 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-20 1:38:20 PM", "Distance": 10.07, "Time": 5435 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-19 1:38:20 PM", "Distance": 8.49, "Time": 4380 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-18 1:38:20 PM", "Distance": 15.23, "Time": 8395 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-17 1:38:20 PM", "Distance": 10.06, "Time": 5366 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-16 1:38:20 PM", "Distance": 3.21, "Time": 1462 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-15 1:38:20 PM", "Distance": 15.55, "Time": 7069 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-14 1:38:20 PM", "Distance": 9.46, "Time": 4978 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-13 1:38:20 PM", "Distance": 15.76, "Time": 7689 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-12 1:38:20 PM", "Distance": 9.26, "Time": 4425 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-11 1:38:20 PM", "Distance": 14.15, "Time": 7291 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-10 1:38:20 PM", "Distance": 8.61, "Time": 4214 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-09 1:38:20 PM", "Distance": 18.96, "Time": 9968 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-08 1:38:20 PM", "Distance": 3.57, "Time": 2037 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-07 1:38:20 PM", "Distance": 10.45, "Time": 5511 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-06 1:38:20 PM", "Distance": 13.66, "Time": 6395 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-05 1:38:20 PM", "Distance": 3.16, "Time": 1659 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-04 1:38:20 PM", "Distance": 12.55, "Time": 5717 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-03 1:38:20 PM", "Distance": 4.43, "Time": 2256 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-02 1:38:20 PM", "Distance": 18.16, "Time": 8852 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-04-01 1:38:20 PM", "Distance": 5.39, "Time": 2541 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-31 1:38:20 PM", "Distance": 7.14, "Time": 3247 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-30 1:38:20 PM", "Distance": 19.83, "Time": 10416 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-29 1:38:20 PM", "Distance": 14.6, "Time": 7430 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-28 1:38:20 PM", "Distance": 3.66, "Time": 1670 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-27 1:38:20 PM", "Distance": 7.19, "Time": 3287 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-26 1:38:20 PM", "Distance": 10.94, "Time": 5123 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-25 1:38:20 PM", "Distance": 17.54, "Time": 8561 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-24 1:38:20 PM", "Distance": 18.12, "Time": 8203 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-23 1:38:20 PM", "Distance": 5.16, "Time": 2850 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${JAMESTOKEN}"'", "UserName": "James", "Date": "2017-03-22 1:38:20 PM", "Distance": 3.96, "Time": 1860 }' > /dev/null

echo "Jogs: Zoe"
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-10 1:38:23 PM", "Distance": 3.75, "Time": 1269 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-09 1:38:23 PM", "Distance": 0.88, "Time": 318 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-08 1:38:23 PM", "Distance": 18.67, "Time": 5976 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-07 1:38:23 PM", "Distance": 15.83, "Time": 5464 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-06 1:38:23 PM", "Distance": 1.29, "Time": 416 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-05 1:38:23 PM", "Distance": 16.07, "Time": 5782 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-04 1:38:23 PM", "Distance": 4.1, "Time": 1471 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-03 1:38:23 PM", "Distance": 6.89, "Time": 2226 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-02 1:38:23 PM", "Distance": 17.82, "Time": 5642 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-05-01 1:38:23 PM", "Distance": 16.82, "Time": 5764 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-30 1:38:23 PM", "Distance": 12.82, "Time": 4384 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-29 1:38:23 PM", "Distance": 0.33, "Time": 118 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-28 1:38:23 PM", "Distance": 8.38, "Time": 2964 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-27 1:38:23 PM", "Distance": 19.42, "Time": 6174 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-26 1:38:23 PM", "Distance": 5.5, "Time": 1985 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-25 1:38:23 PM", "Distance": 10.99, "Time": 3976 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-24 1:38:23 PM", "Distance": 7.9, "Time": 2555 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-23 1:38:23 PM", "Distance": 9.74, "Time": 3505 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-22 1:38:23 PM", "Distance": 19.03, "Time": 6517 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-21 1:38:23 PM", "Distance": 7.76, "Time": 2619 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-20 1:38:23 PM", "Distance": 19.5, "Time": 6346 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-19 1:38:23 PM", "Distance": 18.33, "Time": 6565 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-18 1:38:23 PM", "Distance": 13.62, "Time": 4329 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-17 1:38:23 PM", "Distance": 10.01, "Time": 3433 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-16 1:38:23 PM", "Distance": 13.38, "Time": 4515 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-15 1:38:23 PM", "Distance": 17.58, "Time": 6199 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-14 1:38:23 PM", "Distance": 13.08, "Time": 4031 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-13 1:38:23 PM", "Distance": 1.08, "Time": 340 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-12 1:38:23 PM", "Distance": 7.79, "Time": 2398 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-11 1:38:23 PM", "Distance": 12.31, "Time": 3920 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-10 1:38:23 PM", "Distance": 15.53, "Time": 5646 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-09 1:38:23 PM", "Distance": 0.39, "Time": 141 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-08 1:38:23 PM", "Distance": 2.99, "Time": 952 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-07 1:38:23 PM", "Distance": 13.27, "Time": 4407 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-06 1:38:23 PM", "Distance": 11.69, "Time": 4040 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-05 1:38:23 PM", "Distance": 14.78, "Time": 4885 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-04 1:38:23 PM", "Distance": 8.59, "Time": 2903 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-03 1:38:23 PM", "Distance": 7.23, "Time": 2226 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-02 1:38:23 PM", "Distance": 8.62, "Time": 2680 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-04-01 1:38:23 PM", "Distance": 7.34, "Time": 2396 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-31 1:38:23 PM", "Distance": 13.08, "Time": 4260 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-30 1:38:23 PM", "Distance": 2.45, "Time": 771 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-29 1:38:23 PM", "Distance": 3.24, "Time": 1102 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-28 1:38:23 PM", "Distance": 7.49, "Time": 2536 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-27 1:38:23 PM", "Distance": 12.59, "Time": 4096 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-26 1:38:23 PM", "Distance": 13.37, "Time": 4142 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-25 1:38:23 PM", "Distance": 14.49, "Time": 4744 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-24 1:38:23 PM", "Distance": 12.95, "Time": 4000 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-23 1:38:23 PM", "Distance": 12.53, "Time": 3920 }' > /dev/null
curl -s -u ${BASICAUTH} --request POST http://www.digitalwizardry.ca:5001/api/jog -H "Content-Type: application/json" -d '{ "Token": "'"${ZOETOKEN}"'", "UserName": "Zoe", "Date": "2017-03-22 1:38:23 PM", "Distance": 18.69, "Time": 5835 }' > /dev/null